/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingInfluencerRouteImport } from './routes/onboarding.influencer'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding.brand'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiFetchOgRouteImport } from './routes/api.fetch-og'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInfluencerRoute = OnboardingInfluencerRouteImport.update({
  id: '/onboarding/influencer',
  path: '/onboarding/influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({
  id: '/onboarding/brand',
  path: '/onboarding/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchOgRoute = ApiFetchOgRouteImport.update({
  id: '/api/fetch-og',
  path: '/api/fetch-og',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/api/fetch-og': typeof ApiFetchOgRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/influencer': typeof OnboardingInfluencerRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/api/fetch-og': typeof ApiFetchOgRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/influencer': typeof OnboardingInfluencerRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/api/fetch-og': typeof ApiFetchOgRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/influencer': typeof OnboardingInfluencerRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/requests'
    | '/signup'
    | '/api/fetch-og'
    | '/campaigns/$id'
    | '/onboarding/brand'
    | '/onboarding/influencer'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/requests'
    | '/signup'
    | '/api/fetch-og'
    | '/campaigns/$id'
    | '/onboarding/brand'
    | '/onboarding/influencer'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/requests'
    | '/signup'
    | '/api/fetch-og'
    | '/campaigns/$id'
    | '/onboarding/brand'
    | '/onboarding/influencer'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RequestsRoute: typeof RequestsRoute
  SignupRoute: typeof SignupRoute
  ApiFetchOgRoute: typeof ApiFetchOgRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  OnboardingBrandRoute: typeof OnboardingBrandRoute
  OnboardingInfluencerRoute: typeof OnboardingInfluencerRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/influencer': {
      id: '/onboarding/influencer'
      path: '/onboarding/influencer'
      fullPath: '/onboarding/influencer'
      preLoaderRoute: typeof OnboardingInfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/brand': {
      id: '/onboarding/brand'
      path: '/onboarding/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof OnboardingBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-og': {
      id: '/api/fetch-og'
      path: '/api/fetch-og'
      fullPath: '/api/fetch-og'
      preLoaderRoute: typeof ApiFetchOgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RequestsRoute: RequestsRoute,
  SignupRoute: SignupRoute,
  ApiFetchOgRoute: ApiFetchOgRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  OnboardingBrandRoute: OnboardingBrandRoute,
  OnboardingInfluencerRoute: OnboardingInfluencerRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
